javascript_compressor: yui
javascripts:
  base:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/jquery.rails.js
    - public/javascripts/vendor/shuriken/**/*.js
    - public/javascripts/vendor/youthtree/youth_tree.js
    - public/javascripts/recruitment_platform.js
    - public/javascripts/recruitment_platform/flash.js
  admin:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/jquery.rails.js
    - public/javascripts/vendor/jquery.ui.js
    - public/javascripts/vendor/jquery.timepicker.js
    - public/javascripts/vendor/shuriken/**/*.js
    - public/javascripts/vendor/youthtree/youth_tree.js
    - public/javascripts/vendor/youthtree/youth_tree/forms/date_picker.js
    - public/javascripts/recruitment_platform.js
    - public/javascripts/recruitment_platform/flash.js
    - public/javascripts/recruitment_platform/admin.js
  admin_position_page:
    - public/javascripts/recruitment_platform/admin/paid_field.js
    - public/javascripts/recruitment_platform/admin/question_editor.js
stylesheets:
  base:
    - public/stylesheets/recruitment_platform.css
  admin:
    - public/stylesheets/recruitment_platform-admin.css
    - public/jquery-ui/smoothness/jquery-ui-1.8.custom.css
  base_print:
    - public/stylesheets/recruitment_platform/print.css
